import type { Metadata, Viewport } from "next";
import { Heebo } from "next/font/google";
import { Suspense } from "react";
import { Providers } from "./providers";
import { PostHogPageview } from "@/components/PostHogPageview";
import { BackgroundDepth } from "@/components/background";
import "./globals.css";

/**
 * LCP Strategy:
 * - Heebo font is preloaded via Next.js font optimization (preload: true)
 * - Hero section uses pure CSS phone mockup (no images to preload)
 * - Headline text is the LCP element, server-rendered for immediate visibility
 * - ActivityFeed animation runs after initial paint (client-only, non-blocking)
 * - No additional preload hints needed - hero is text + CSS only
 */

const heebo = Heebo({
  subsets: ["hebrew"],
  display: "swap",
  weight: ["400", "500", "700"],
  variable: "--font-heebo",
  fallback: ["Arial", "sans-serif"],
  preload: true,
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#ffffff",
};

/**
 * SEO Metadata Configuration
 * - Hebrew-optimized title, description, and keywords
 * - Open Graph with he_IL locale for proper Hebrew social previews
 * - Twitter card for social sharing
 * - metadataBase for canonical URL generation
 */
export const metadata: Metadata = {
  metadataBase: new URL("https://findo.co.il"),

  // Hebrew title and description
  title: {
    default: "Findo - יותר לקוחות, פחות עבודה | צמיחה אוטומטית לעסקים",
    template: "%s | Findo",
  },
  description: "מערכת אוטומטית לניהול ביקורות, איסוף לידים ואופטימיזציה של Google Business Profile. העסק שלך עובד 24/7 - אתה לא צריך.",

  // Hebrew keywords
  keywords: [
    "ניהול ביקורות",
    "איסוף לידים",
    "Google Business Profile",
    "אוטומציה לעסקים",
    "שיווק דיגיטלי",
    "עסקים קטנים ובינוניים",
    "SMB",
    "לידים",
    "ביקורות גוגל",
    "צמיחה עסקית",
  ],

  // Authorship and site info
  authors: [{ name: "Findo" }],
  creator: "Findo",
  publisher: "Findo",

  // Open Graph - Hebrew locale
  // Note: OG images are auto-generated by app/opengraph-image.tsx
  openGraph: {
    type: "website",
    locale: "he_IL",
    url: "https://findo.co.il",
    siteName: "Findo",
    title: "Findo - יותר לקוחות, פחות עבודה",
    description: "מערכת אוטומטית לניהול ביקורות, איסוף לידים ואופטימיזציה של Google Business Profile. העסק שלך עובד 24/7 - אתה לא צריך.",
  },

  // Twitter card
  // Note: Twitter images are auto-generated by app/opengraph-image.tsx
  twitter: {
    card: "summary_large_image",
    title: "Findo - יותר לקוחות, פחות עבודה",
    description: "מערכת אוטומטית לניהול ביקורות, איסוף לידים ואופטימיזציה של Google Business Profile.",
  },

  // Robots configuration
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Verification (placeholders for future setup)
  // verification: {
  //   google: "google-site-verification-code",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl" className={heebo.variable} suppressHydrationWarning>
      <body className={`${heebo.className} antialiased`}>
        <BackgroundDepth />
        <Providers>
          <Suspense fallback={null}>
            <PostHogPageview />
          </Suspense>
          {children}
        </Providers>
      </body>
    </html>
  );
}
